# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

# There are many options which enable SPI, so make this library available

obj-$(CONFIG_AW_SPI) += spi-sunxi.o calibrate/spi-sunxi-calibrate.o

obj-$(CONFIG_AW_SPIF) += spif-sunxi.o
obj-$(CONFIG_SPI_FLASH) += spi-mem.o