# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2018www.allwinner.tech
#
# Based on some other board Makefile
#
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-$(CONFIG_SUNXI_SPRITE)  += sprite_download.o firmware/imgdecode.o sprite_erase.o sprite_common.o
obj-$(CONFIG_SUNXI_CARD_PRODUCT) += sprite_main.o sprite_card.o

obj-y += sparse/sparse.o sprite_verify.o sprite_privatedata.o

obj-$(CONFIG_SUNXI_SPRITE_CARTOON)	+= cartoon/
obj-$(CONFIG_SUNXI_AUTO_UPDATE) += sprite_auto_update.o

obj-$(CONFIG_SUNXI_SPRITE_LED)	+= sprite_led.o

