subdir-ccflags-y += -I$(srctree)/bsp/board/sunxi/certification/IEC60730/library/include
subdir-ccflags-y += -I$(srctree)/bsp/board/sunxi/certification/IEC60730/app

obj-y += app/aw_check_common.o
obj-y += library/src/aw_cpu_check.o
obj-y += library/src/aw_ram_check.o
obj-y += library/src/aw_pc_check.o
obj-y += library/src/aw_check.o
obj-y += library/src/aw_clk_check.o
obj-y += library/src/aw_rom_check.o
obj-y += library/src/aw_interrupt_check.o

obj-y += library/src/platform/

