# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2001
# Erik Theisen, Wave 7 Optics, etheisen@mindspring.com.

obj-$(CONFIG_AW_PWM)		+= sunxi_pwm.o
obj-$(CONFIG_AW_PWMCS)		+= sunxi_pwmcs.o
