obj-$(CONFIG_SOUND_SUNXI_SOC_AUDIOCODEC) += sunxi-codec.o
obj-$(CONFIG_SOUND_SUNXI_SUN55IW6_CODEC)	+= sun55iw6-codec.o
obj-$(CONFIG_SOUND_SUNXI_SUN8IW22_CODEC)	+= sun8iw22-codec.o
obj-$(CONFIG_SOUND_SUNXI_SOC_RWFUNC) += sunxi_rw_func.o
obj-$(CONFIG_SOUND_SUNXI_SOC_SOUND) += sunxi_sound.o
obj-$(CONFIG_SOUND_SUNXI_BOOT_TONE)  += sunxi_boot_tone.o
