# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2019

pcie_sunxi_ep-objs := pcie-sunxi-ep.o  pcie-sunxi-plat.o
pcie_sunxi_rc-objs := pcie-sunxi-rc.o  pcie-sunxi-plat.o
obj-$(CONFIG_PCIE_ALLWINNER_EP) += pcie_sunxi_ep.o
obj-$(CONFIG_PCIE_ALLWINNER_RC) += pcie_sunxi_rc.o