#
# Copyright (C) 2018 Amarula Solutions.
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-$(CONFIG_AW_CLK) += clk_sunxi.o

obj-$(CONFIG_AW_CLK_SUN8IW21) += clk_sun8iw21.o
obj-$(CONFIG_AW_CLK_SUN65IW1) += clk_sun65iw1.o
obj-$(CONFIG_AW_CLK_SUN55IW6) += clk_sun55iw6.o
obj-$(CONFIG_AW_CLK_SUN55IW6) += clk_sun55iw6_r.o
obj-$(CONFIG_AW_CLK_SUN8IW22) += clk_sun8iw22.o
obj-$(CONFIG_AW_CLK_SUN252IW1) += clk_sun252iw1.o
