# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2015 Allwinnertech, Inc.
# Tyle <tyle at allwinnertech.com>
#
#

obj-$(CONFIG_BOOT_GUI) += cmd_sunxi_bmp.o
obj-$(CONFIG_SUNXI_SPINOR_BMP) +=sunxi_load_bmp.o
obj-$(CONFIG_SUNXI_TINYJPEG_DECODER) += tinyjpegdecoder/
obj-$(CONFIG_CMD_SUNXI_JPEG) +=sunxi_load_jpeg.o
