/* SPDX-License-Identifier: GPL-2.0-only */
/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY'S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS'SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY'S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef __DMA_ISOLATION_SUN8IW22_H__
#define __DMA_ISOLATION_SUN8IW22_H__

#include <asm/arch/clock.h>

#define MAX_DMA_CHAN_NUM	16
#define MAX_DMA_MASK_REG_NUM	4
#define FIX_MASTER_MASK		0x1F
#define UNKNOW_MASTER_ID	-1
#define MAX_DMA_DEV_NUM		2
#define MAX_GROUP_NUM		2

#define MASTER_ID_NEGATE

#define DMA_MASTER_ID_CFG_OFFSET	0x70
#define DMA_MASTER_MASK_CFG_OFFSET	0x74
#define DMA_MASTER_ID_OFFSET	0x84

#define DMA_MASTER_ID_CFG_BIT_MASK		0x3
#define DMA_MASTER_ID_CFG_BIT_OFFSET(n)		(n * 2)

#define DMA_MASTER_MASK_BIT_MASK	0x1f
#define DMA_MASTER_MASK_BIT_OFFSET(n)	((n % 4) * 8)
#define DMA_MASTER_MASK_REG_OFFSET(n)	(0x4 * n)

#define DMA_MASTER_ID_BIT_MASK		0x1f
#define DMA_MASTER_ID_BIT_OFFSET(n)	(n * 8)

#define CHAN_REG_OFFSET(n)	(n / 4)
#define FIX_DMA_MASTER_ID_VAL	0x90

int dma_max_chan[MAX_DMA_DEV_NUM] = {16, 8};
int dma_max_mask_num[MAX_DMA_DEV_NUM] = {4, 2};
int dma_master_mask_list[MAX_GROUP_NUM] = {0};
int dma_base[MAX_DMA_DEV_NUM] = {SUNXI_DMAC0_BASE, SUNXI_DMAC1_BASE};

#define DMA_MAX_CPU_NUM 5
int dma_cpu_soft_id[DMA_MAX_CPU_NUM] = {0x0, 0x1, 0x2, 0x3, 0x4};
int dma_cpu_ic_id[DMA_MAX_CPU_NUM] = {0x0, 0x1, 0x2, 0x3, 0x9};

static inline void dma_iso_reset_clk(void)
{
	asrm_port_writel(0x00000000, (void *)SUNXI_CCMU_BASE + DMA0_GAR_REG);
	asrm_port_writel(0x00000000, (void *)SUNXI_CCMU_BASE + DMA1_GAR_REG);
}

static inline void dma_iso_enable_clk(void)
{
	asrm_port_writel(0x00010001, (void *)SUNXI_CCMU_BASE + DMA0_GAR_REG);
	asrm_port_writel(0x00010001, (void *)SUNXI_CCMU_BASE + DMA1_GAR_REG);
}

static inline void dma_iso_disable_clk(void)
{
	asrm_port_writel(0x00010000, (void *)SUNXI_CCMU_BASE + DMA0_GAR_REG);
	asrm_port_writel(0x00010000, (void *)SUNXI_CCMU_BASE + DMA1_GAR_REG);
}

#endif  /* __DMA_ISOLATION_SUN8IW22_H__ */
