# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2017 Andes Technology Corporation.
# Rick Chen, Andes Technology Corporation <rick@andestech.com>

head-y := cpu/$(CPU)/start.o
libs-y += cpu/$(CPU)/
libs-y += cpu/
libs-y += lib/
